# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kms_plugin_vault_pb2 as kms__plugin__vault__pb2


class KeyManagementServiceStub(object):
  """This service defines the public APIs for remote KMS provider.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Version = channel.unary_unary(
        '/v1beta1.KeyManagementService/Version',
        request_serializer=kms__plugin__vault__pb2.VersionRequest.SerializeToString,
        response_deserializer=kms__plugin__vault__pb2.VersionResponse.FromString,
        )
    self.Decrypt = channel.unary_unary(
        '/v1beta1.KeyManagementService/Decrypt',
        request_serializer=kms__plugin__vault__pb2.DecryptRequest.SerializeToString,
        response_deserializer=kms__plugin__vault__pb2.DecryptResponse.FromString,
        )
    self.Encrypt = channel.unary_unary(
        '/v1beta1.KeyManagementService/Encrypt',
        request_serializer=kms__plugin__vault__pb2.EncryptRequest.SerializeToString,
        response_deserializer=kms__plugin__vault__pb2.EncryptResponse.FromString,
        )


class KeyManagementServiceServicer(object):
  """This service defines the public APIs for remote KMS provider.
  """

  def Version(self, request, context):
    """Version returns the runtime name and runtime version of the KMS provider.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Decrypt(self, request, context):
    """Execute decryption operation in KMS provider.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Encrypt(self, request, context):
    """Execute encryption operation in KMS provider.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeyManagementServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Version': grpc.unary_unary_rpc_method_handler(
          servicer.Version,
          request_deserializer=kms__plugin__vault__pb2.VersionRequest.FromString,
          response_serializer=kms__plugin__vault__pb2.VersionResponse.SerializeToString,
      ),
      'Decrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Decrypt,
          request_deserializer=kms__plugin__vault__pb2.DecryptRequest.FromString,
          response_serializer=kms__plugin__vault__pb2.DecryptResponse.SerializeToString,
      ),
      'Encrypt': grpc.unary_unary_rpc_method_handler(
          servicer.Encrypt,
          request_deserializer=kms__plugin__vault__pb2.EncryptRequest.FromString,
          response_serializer=kms__plugin__vault__pb2.EncryptResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'v1beta1.KeyManagementService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
