# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kms_plugin_vault.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kms_plugin_vault.proto',
  package='v1beta1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16kms_plugin_vault.proto\x12\x07v1beta1\"!\n\x0eVersionRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"Q\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0cruntime_name\x18\x02 \x01(\t\x12\x17\n\x0fruntime_version\x18\x03 \x01(\t\"1\n\x0e\x44\x65\x63ryptRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06\x63ipher\x18\x02 \x01(\x0c\" \n\x0f\x44\x65\x63ryptResponse\x12\r\n\x05plain\x18\x01 \x01(\x0c\"0\n\x0e\x45ncryptRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\r\n\x05plain\x18\x02 \x01(\x0c\"!\n\x0f\x45ncryptResponse\x12\x0e\n\x06\x63ipher\x18\x01 \x01(\x0c\x32\xd6\x01\n\x14KeyManagementService\x12>\n\x07Version\x12\x17.v1beta1.VersionRequest\x1a\x18.v1beta1.VersionResponse\"\x00\x12>\n\x07\x44\x65\x63rypt\x12\x17.v1beta1.DecryptRequest\x1a\x18.v1beta1.DecryptResponse\"\x00\x12>\n\x07\x45ncrypt\x12\x17.v1beta1.EncryptRequest\x1a\x18.v1beta1.EncryptResponse\"\x00\x62\x06proto3')
)




_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='v1beta1.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='v1beta1.VersionRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=68,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='v1beta1.VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='v1beta1.VersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtime_name', full_name='v1beta1.VersionResponse.runtime_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtime_version', full_name='v1beta1.VersionResponse.runtime_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=151,
)


_DECRYPTREQUEST = _descriptor.Descriptor(
  name='DecryptRequest',
  full_name='v1beta1.DecryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='v1beta1.DecryptRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cipher', full_name='v1beta1.DecryptRequest.cipher', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=202,
)


_DECRYPTRESPONSE = _descriptor.Descriptor(
  name='DecryptResponse',
  full_name='v1beta1.DecryptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plain', full_name='v1beta1.DecryptResponse.plain', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=236,
)


_ENCRYPTREQUEST = _descriptor.Descriptor(
  name='EncryptRequest',
  full_name='v1beta1.EncryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='v1beta1.EncryptRequest.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plain', full_name='v1beta1.EncryptRequest.plain', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=286,
)


_ENCRYPTRESPONSE = _descriptor.Descriptor(
  name='EncryptResponse',
  full_name='v1beta1.EncryptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cipher', full_name='v1beta1.EncryptResponse.cipher', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=321,
)

DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
DESCRIPTOR.message_types_by_name['DecryptRequest'] = _DECRYPTREQUEST
DESCRIPTOR.message_types_by_name['DecryptResponse'] = _DECRYPTRESPONSE
DESCRIPTOR.message_types_by_name['EncryptRequest'] = _ENCRYPTREQUEST
DESCRIPTOR.message_types_by_name['EncryptResponse'] = _ENCRYPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREQUEST,
  __module__ = 'kms_plugin_vault_pb2'
  # @@protoc_insertion_point(class_scope:v1beta1.VersionRequest)
  ))
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONRESPONSE,
  __module__ = 'kms_plugin_vault_pb2'
  # @@protoc_insertion_point(class_scope:v1beta1.VersionResponse)
  ))
_sym_db.RegisterMessage(VersionResponse)

DecryptRequest = _reflection.GeneratedProtocolMessageType('DecryptRequest', (_message.Message,), dict(
  DESCRIPTOR = _DECRYPTREQUEST,
  __module__ = 'kms_plugin_vault_pb2'
  # @@protoc_insertion_point(class_scope:v1beta1.DecryptRequest)
  ))
_sym_db.RegisterMessage(DecryptRequest)

DecryptResponse = _reflection.GeneratedProtocolMessageType('DecryptResponse', (_message.Message,), dict(
  DESCRIPTOR = _DECRYPTRESPONSE,
  __module__ = 'kms_plugin_vault_pb2'
  # @@protoc_insertion_point(class_scope:v1beta1.DecryptResponse)
  ))
_sym_db.RegisterMessage(DecryptResponse)

EncryptRequest = _reflection.GeneratedProtocolMessageType('EncryptRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTREQUEST,
  __module__ = 'kms_plugin_vault_pb2'
  # @@protoc_insertion_point(class_scope:v1beta1.EncryptRequest)
  ))
_sym_db.RegisterMessage(EncryptRequest)

EncryptResponse = _reflection.GeneratedProtocolMessageType('EncryptResponse', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTRESPONSE,
  __module__ = 'kms_plugin_vault_pb2'
  # @@protoc_insertion_point(class_scope:v1beta1.EncryptResponse)
  ))
_sym_db.RegisterMessage(EncryptResponse)



_KEYMANAGEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='KeyManagementService',
  full_name='v1beta1.KeyManagementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=324,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='Version',
    full_name='v1beta1.KeyManagementService.Version',
    index=0,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Decrypt',
    full_name='v1beta1.KeyManagementService.Decrypt',
    index=1,
    containing_service=None,
    input_type=_DECRYPTREQUEST,
    output_type=_DECRYPTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Encrypt',
    full_name='v1beta1.KeyManagementService.Encrypt',
    index=2,
    containing_service=None,
    input_type=_ENCRYPTREQUEST,
    output_type=_ENCRYPTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYMANAGEMENTSERVICE)

DESCRIPTOR.services_by_name['KeyManagementService'] = _KEYMANAGEMENTSERVICE

# @@protoc_insertion_point(module_scope)
